DROP TABLE IF EXISTS "Order";
DROP TABLE IF EXISTS Items;

CREATE TABLE "Order" (
  orderId TEXT PRIMARY KEY,
  value INTEGER NOT NULL,
  creationDate TEXT NOT NULL
);

CREATE TABLE Items (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  orderId TEXT NOT NULL,
  productId INTEGER NOT NULL,
  quantity INTEGER NOT NULL,
  price INTEGER NOT NULL,
  FOREIGN KEY (orderId) REFERENCES "Order"(orderId) ON DELETE CASCADE
);
